### ISSUE TITLE
Stopped midway through article

### ISSUE THREAD

**Issue by benfrancis314** [benfrancis314/reading_project#100]
Unidentified problem. Occurred on: https://en.wikipedia.org/wiki/Elizabeth_I. Stops at "Accession".

**Comment by benfrancis314** [comment]
I couldn't replicate this again ... weird. Maybe something on my end, but I'll leave it up as a thing to be on the look out for

**Comment by benfrancis314** [comment]
It happened again, not sure what variables were controlled.

**Comment by benfrancis314** [comment]
Also occurred here: https://en.wikipedia.org/wiki/Prime_number at Definition and Examples

**Comment by sjonany** [comment]
Fixed with https://github.com/benfrancis314/reading_project/commit/df0faa55ac69aa900fe4ff32482fd1f9c50711be
