### ISSUE TITLE
Some articles that are too big cause browser crashes

### ISSUE THREAD

**Issue by benfrancis314** [benfrancis314/reading_project#103]
This feels like a while, from a users perspective. Is this due to one step in particular?

**Comment by sjonany** [comment]
On https://en.wikipedia.org/wiki/Prime_number, on my shitty laptop,
detectSentenceBoundary() can range from
0.619 s
3.942 s
..
And one instance it waited for a few seconds that caused my browser to crash.

Note that this is a page with a lot of math symbols. And just as in https://github.com/benfrancis314/reading_project/issues/74, each math symbol could for some reason result in a crap load of sentence boundaries.

**Comment by benfrancis314** [comment]
Nice job isolating it!!

**Comment by sjonany** [comment]
Some non-mutually exclusive fixes:
- If detect math el, skip document and just say 'we dont support' for now
- Actually fix math el handling
- If number of sentences >> x, skip
- Implement a streaming sentence processing logic where you don't preprocess everything at once, but preprocess only the K neighboring paragraphs (much trickier to implement, but that's what video games do)

**Comment by benfrancis314** [comment]
I think 3 strikes a good balance at the moment between easiness and user not noticing it (though all seem like fine options)

**Comment by sjonany** [comment]
Detecting sentence boundaries done in **36.634 s**
-- I think my browser was about to crash this time.

I have a possible fix for the math problem.
Impose a min number of non-empty chars that each sentence should have. If too small, merge the sentence with the next.
I think this would solve the math issue, which then reduces the number of sentence boundaries, which then makes most pages renderable.

Still need to handle "too big won't parse" someday tho. I wanna see if this fix works first.

**Comment by sjonany** [comment]
For reference,
https://en.wikipedia.org/wiki/Language has 500 ish words
ttps://en.wikipedia.org/wiki/Prime_number has 2800 ish words because of missegmentation of math els.

**Comment by sjonany** [comment]
Even for language, for my crappy computer, sometimes
DEBUG: Number of sentences = 511
content_script.js:17 DEBUG: Detecting sentence boundaries done in **19.18 s**

**Comment by sjonany** [comment]
https://github.com/benfrancis314/reading_project/pull/108
