### ISSUE TITLE
Next sentence bug

### ISSUE THREAD

**Issue by sjonany** [benfrancis314/reading_project#13]
https://www.reddit.com/r/LucidDreaming/comments/1p1107/richard_feynmans_account_of_his_investigations/
After "The knocking is still going, I wake up, and", for some reason moveNext causes the tracker to disappear.
However, going backward from the paragraph before it, after 2 clicks to cross the " . . .",  the tracker reappears.

**Comment by sjonany** [comment]
Hm after this pull https://github.com/benfrancis314/reading_project/pull/15
The only problem is that the ". . ." is not highlighted.

**Comment by benfrancis314** [comment]
I've subsumed this into issue #9 (see comments in that issue), so am going to close this issue. Feel free to reopen though if I have inaccurately interpreted the issue

**Comment by sjonany** [comment]
Sounds good. Thank you!
