### ISSUE TITLE
Window parsing should NOT happen unless user first activates the extension / app is active

### ISSUE THREAD

**Issue by sjonany** [benfrancis314/reading_project#160]
Otherwise every webpage will incur extra parsing cost
Ideally content script when app is off == no parsing, just setting up key listener

** not sure how important.

**Comment by sjonany** [comment]
Waaaait. Actually I'm not sure about this.
The adv of current approach is that user won't notice the loading time when they press r -- cos doc would have been preprocessed.

**Comment by benfrancis314** [comment]
Hmmmm this is a weird ethical question: 

A. It incurs a cost on their browser for anything they ever open; but they won't know that it is coming from this extension (unless they're hella tech savvy). 

B. Because of this, it makes our extension open up virtually instantly, when they want to use it. 

So the average browser experience may suffer, but our extension experience will be enhanced. 
Hmmmmmmmm

**Comment by benfrancis314** [comment]
Compare: 

Grammarly is always running whatever AI thing it does to analyze my text. I don't seem to even notice this/care. However, it's possible it is only looking for this when I start typing

**Comment by sjonany** [comment]
When in doubt, delegate to setting LOL.
I can see users who would like either.

What about:
- keep current behavior, because it is a reasonable pattern than users
might subscribe to long term anyway
- an action item to delay parsing after r as a feature. -- not sure how
important

**Comment by sjonany** [comment]
On second thought.
It's possible that our app screws things up on some pages when we setup. --
we are mutating the Dom tree afterall

The way is it rn, if a users fav page is always broken thanks to the
compulsory preproc they'll uninstall the app most likely

Hmm now I'm leaning towards 'preproc after r' as a default, and the nice to
have option be -- autoparse doc asap to reduce load time

**Comment by benfrancis314** [comment]
Ehh I think that having that as a setting may cause more confusion than it's worth, especially for the non-technical crowd. (And if we wanted to have an "esoteric settings"  section for adjusting minutiae like this [perhaps not a terrible idea for subtle user testing], it'd be a whole thing). 

I agree with second comment, "Hmm now I'm leaning towards 'preproc after r' as a default, and the nice to
have option be -- autoparse doc asap to reduce load time", esp if we have a little loader animation that will make the wait time more forgiving

**Comment by benfrancis314** [comment]
Plus I think that's probably on the better ethical side; we're also not parsing through things they may not want us too, like passwords etc

**Comment by sjonany** [comment]
Good point. Ok! This is a pretty important feature request then.

I can get to it after 4pm PST if u wanna work on the other items. But feel
free to work on this if u want too
Thanks for the discussion!

**Comment by benfrancis314** [comment]
Ok sounds good, thanks for thinking of it!

**Comment by sjonany** [comment]
https://github.com/benfrancis314/reading_project/pull/166
