### ISSUE TITLE
Equations appear to throw it off

### ISSUE THREAD

**Issue by benfrancis314** [benfrancis314/reading_project#74]
See: https://en.wikipedia.org/wiki/Monstrous_moonshine

**Comment by sjonany** [comment]
oof this was a very good find. extension v hard to use here.

**Comment by sjonany** [comment]
Here is an example of the problem.
All these <math> element unfortunately is registered in text(), and is wonky. My understanding is that mark.js offsets are also against .text() indices. Hrmm... 

[HTML]
<math xmlns="http://www.w3.org/1998/Math/MathML" alttext="{\displaystyle V^{\natural }}" id="ui-id-619"><mark data-markjs="true" class="trackerClass trackerHighlighterGreenShadowBlue">
</mark>  <semantics id="ui-id-620">
    <mrow class="MJX-TeXAtom-ORD">
      <mstyle displaystyle="true" scriptlevel="0">
        <msup>
          <mi>V</mi>
          <mrow class="MJX-TeXAtom-ORD">
            <mi mathvariant="normal">♮</mi>
          </mrow>
        </msup>
      </mstyle>
    </mrow>
    <annotation encoding="application/x-tex" id="ui-id-621">{\displaystyle V^{\natural }}</annotation>
  </semantics>
</math>

[.text()]
 The case of order 2 requires the existence of a form of 
  
    
      
        
          V
          
            ♮
          
        
      
    
    {\displaystyle V^{\natural }}
  
 over a 2-adic ring, i.e., a construction

**Comment by sjonany** [comment]
Even worse is that the stuff inside math htmls don't have a valid .top, causing back movements to scroll to the top of the page.

**Comment by benfrancis314** [comment]
Hmmm at least this is an edge case, I feel like users would be forgiving of it since it is reasonable that equations would cause confusion
